feat: improvement to rpc package
suneettipirneni/discord.js pull request #2
Opened 2022-09-23 16:20 UTC by xhayper

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

2022-09-23 18:13 UTC, OfficialSirH approved these changes
Looking pretty epicc if I do say so myself

2022-09-24 18:14 UTC, almeidx requested changes

2022-09-24 18:14 UTC, almeidx commented on packages/rpc/src/client.ts
>  import { transports } from './transports';
Can't you just do this?
```suggestion
import { RPCError } from './error.js';
import { transports } from './transports/index.js';
```

2022-09-24 18:14 UTC, almeidx commented on packages/rpc/src/client.ts
> +import { pid as getPid } from './util';
Can't comment on deleted lines 🙄 
```suggestion
import { RPCCommands, RPCEvents, type LobbyType, RelationshipType, RPCErrorCodes } from './typings/types.js';
import { pid as getPid } from './util.js';
```

2022-09-24 18:14 UTC, almeidx commented on packages/rpc/src/error.ts
> +import { RPCErrorCodes } from './typings/types';
```suggestion
import { RPCErrorCodes } from './typings/types.js';
```

2022-09-24 18:14 UTC, almeidx commented on packages/rpc/src/index.ts
>  import { register as registerUtil } from './util';
```suggestion
import { register as registerUtil } from './util.js';
```

2022-09-24 18:14 UTC, almeidx commented on packages/rpc/src/index.ts
> +export { RPCClient as Client } from './client';
```suggestion
export { RPCClient as Client } from './client.js';
```

2022-09-24 18:14 UTC, almeidx commented on packages/rpc/src/transports/index.ts
>  import { WebSocketTransport as websocket } from './websocket';
```suggestion
import { default as ipc } from './ipc.js';
import { WebSocketTransport as websocket } from './websocket.js';
```

2022-09-30 07:01 UTC, merged

2022-09-30 07:07 UTC, xhayper commented
this was caused by me being bad at git, sorry.